site_name: Projeto BOSS - Unity
nav: 
 - Home: 'index.md'
 - Conceitos: 'concepts.md'
 - Jogo: 'game.md'
 - Visão de produto e projeto: 
    - Visão de produto: 'product.md'
    - Visão de projeto: 'project.md'
    - Processos de desenvolvimento de software: 'devprocess.md'
 - Backlog: 'backlog.md'
 - Padrões de desenvolvimento: 'patterns.md'
 - Artes e referências: 'references.md'
 - Roadmap e Sprints: 
    - Roadmap e Sprints: 'sprints.md'
    - Sprint (28/02/24 - 06/03/24): 'sprint1.md'
    - Sprint (06/03/24 - 13/03/24): 'sprint2.md'
    - Sprint (13/03/24 - 20/03/24): 'sprint3.md'
    - Sprint (20/03/24 - 27/03/24): 'sprint4.md'
    - Sprint (27/03/24 - 02/04/24): 'sprint5.md'
    - Sprint (02/04/24 - 08/04/24): 'sprint6.md'
    - Sprint (09/04/24 - 16/04/24): 'sprint7.md'


theme:
  name: material
  language: pt
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
extra_css:
  - stylesheets/extra.css
extra:
  generator: false