name: Acquire activation file
on:
    workflow_dispatch: {}
jobs:
    activation:
    name: Ativação da Licença Unity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Solicitar Arquivo de Ativação
        id: get_activation_file
        uses: game-ci/unity-request-activation-file@v2

      - name: Armazenar Arquivo de Ativação como Artefato
        uses: actions/upload-artifact@v3
        with:
          name: ActivationFile
          path: ${{ steps.get_activation_file.outputs.filePath }}